//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DataDictionary", typeof(DataDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement.
        /// </summary>
        public static string Advertisement {
            get {
                return ResourceManager.GetString("Advertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agriculture.
        /// </summary>
        public static string Agriculture {
            get {
                return ResourceManager.GetString("Agriculture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparel.
        /// </summary>
        public static string Apparel {
            get {
                return ResourceManager.GetString("Apparel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking.
        /// </summary>
        public static string Banking {
            get {
                return ResourceManager.GetString("Banking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biotechnology.
        /// </summary>
        public static string Biotechnology {
            get {
                return ResourceManager.GetString("Biotechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemicals.
        /// </summary>
        public static string Chemicals {
            get {
                return ResourceManager.GetString("Chemicals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold.
        /// </summary>
        public static string Cold {
            get {
                return ResourceManager.GetString("Cold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communications.
        /// </summary>
        public static string Communications {
            get {
                return ResourceManager.GetString("Communications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction.
        /// </summary>
        public static string Construction {
            get {
                return ResourceManager.GetString("Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulting.
        /// </summary>
        public static string Consulting {
            get {
                return ResourceManager.GetString("Consulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacted.
        /// </summary>
        public static string Contacted {
            get {
                return ResourceManager.GetString("Contacted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Date.
        /// </summary>
        public static string CurrentDate {
            get {
                return ResourceManager.GetString("CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Coupon.
        /// </summary>
        public static string DiscountCoupon {
            get {
                return ResourceManager.GetString("DiscountCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Percent.
        /// </summary>
        public static string DiscountPercent {
            get {
                return ResourceManager.GetString("DiscountPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr..
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        public static string Electronics {
            get {
                return ResourceManager.GetString("Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Verification Key.
        /// </summary>
        public static string EmailAddressVerificationKey {
            get {
                return ResourceManager.GetString("EmailAddressVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering.
        /// </summary>
        public static string Engineering {
            get {
                return ResourceManager.GetString("Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        public static string Entertainment {
            get {
                return ResourceManager.GetString("Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental.
        /// </summary>
        public static string Environmental {
            get {
                return ResourceManager.GetString("Environmental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Referral.
        /// </summary>
        public static string ExternalReferral {
            get {
                return ResourceManager.GetString("ExternalReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Name.
        /// </summary>
        public static string FeatureName {
            get {
                return ResourceManager.GetString("FeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government.
        /// </summary>
        public static string Government {
            get {
                return ResourceManager.GetString("Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthcare.
        /// </summary>
        public static string Healthcare {
            get {
                return ResourceManager.GetString("Healthcare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitality.
        /// </summary>
        public static string Hospitality {
            get {
                return ResourceManager.GetString("Hospitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot.
        /// </summary>
        public static string Hot {
            get {
                return ResourceManager.GetString("Hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indstry.
        /// </summary>
        public static string Indstry {
            get {
                return ResourceManager.GetString("Indstry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Store.
        /// </summary>
        public static string InStore {
            get {
                return ResourceManager.GetString("InStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        public static string Insurance {
            get {
                return ResourceManager.GetString("Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Mobile Number Verified.
        /// </summary>
        public static string IsCellPhoneNumberVerified {
            get {
                return ResourceManager.GetString("IsCellPhoneNumberVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Email Address Verified.
        /// </summary>
        public static string IsEmailAddressVerified {
            get {
                return ResourceManager.GetString("IsEmailAddressVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead.
        /// </summary>
        public static string Lead {
            get {
                return ResourceManager.GetString("Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Source.
        /// </summary>
        public static string LeadSource {
            get {
                return ResourceManager.GetString("LeadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Status.
        /// </summary>
        public static string LeadStatus {
            get {
                return ResourceManager.GetString("LeadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machinery.
        /// </summary>
        public static string Machinery {
            get {
                return ResourceManager.GetString("Machinery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing.
        /// </summary>
        public static string Manufacturing {
            get {
                return ResourceManager.GetString("Manufacturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Verification Key.
        /// </summary>
        public static string MobileVerificationKey {
            get {
                return ResourceManager.GetString("MobileVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr..
        /// </summary>
        public static string Mr {
            get {
                return ResourceManager.GetString("Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs..
        /// </summary>
        public static string Mrs {
            get {
                return ResourceManager.GetString("Mrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms..
        /// </summary>
        public static string Ms {
            get {
                return ResourceManager.GetString("Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Code.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Identity.
        /// </summary>
        public static string NationalIdentity {
            get {
                return ResourceManager.GetString("NationalIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --None--.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not For Profit.
        /// </summary>
        public static string NotForProfit {
            get {
                return ResourceManager.GetString("NotForProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Site.
        /// </summary>
        public static string OnSite {
            get {
                return ResourceManager.GetString("OnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Name.
        /// </summary>
        public static string PackageName {
            get {
                return ResourceManager.GetString("PackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof..
        /// </summary>
        public static string Professor {
            get {
                return ResourceManager.GetString("Professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer.
        /// </summary>
        public static string Programmer {
            get {
                return ResourceManager.GetString("Programmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Name.
        /// </summary>
        public static string ProvinceName {
            get {
                return ResourceManager.GetString("ProvinceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualified.
        /// </summary>
        public static string Qualified {
            get {
                return ResourceManager.GetString("Qualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreation.
        /// </summary>
        public static string Recreation {
            get {
                return ResourceManager.GetString("Recreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail.
        /// </summary>
        public static string Retail {
            get {
                return ResourceManager.GetString("Retail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salutation.
        /// </summary>
        public static string Salutation {
            get {
                return ResourceManager.GetString("Salutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        public static string Technology {
            get {
                return ResourceManager.GetString("Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telecommunications.
        /// </summary>
        public static string Telecommunications {
            get {
                return ResourceManager.GetString("Telecommunications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation.
        /// </summary>
        public static string Transportation {
            get {
                return ResourceManager.GetString("Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unqualified.
        /// </summary>
        public static string Unqualified {
            get {
                return ResourceManager.GetString("Unqualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string Utilities {
            get {
                return ResourceManager.GetString("Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Date From.
        /// </summary>
        public static string ValidDateFrom {
            get {
                return ResourceManager.GetString("ValidDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Date To.
        /// </summary>
        public static string ValidDateTo {
            get {
                return ResourceManager.GetString("ValidDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm.
        /// </summary>
        public static string Warm {
            get {
                return ResourceManager.GetString("Warm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word of mouth.
        /// </summary>
        public static string Wordofmouth {
            get {
                return ResourceManager.GetString("Wordofmouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
    }
}
