//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.Validations", typeof(Validations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید دقیقا {1} رقم باشد!.
        /// </summary>
        public static string FixLengthNumeric {
            get {
                return ResourceManager.GetString("FixLengthNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بزرگ‌تر از {1} باشد!.
        /// </summary>
        public static string GreaterThan_FieldValue {
            get {
                return ResourceManager.GetString("GreaterThan_FieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بزرگ‌تر از مقدار فیلد {1} باشد!.
        /// </summary>
        public static string GreaterThan_TwoFields {
            get {
                return ResourceManager.GetString("GreaterThan_TwoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بزرگ‌تر یا مساوی {1} باشد!.
        /// </summary>
        public static string GreaterThanOrEqualTo_FieldValue {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualTo_FieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بزرگ‌تر یا مساوی مقدار فیلد {1} باشد!.
        /// </summary>
        public static string GreaterThanOrEqualTo_TwoFields {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualTo_TwoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد {0} صحیح نمی‌باشد!.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول فیلد {0} می‌تواند حداکثر {1} کاراکتر باشد!.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول فیلد {0} باید حداقل {1} کاراکتر باشد!.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} یافت نشد!.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بزرگ‌تر یا مساوی {1} و کوچک‌تر یا مساوی {2} باشد..
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} معتبر نمی‌باشد!.
        /// </summary>
        public static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تکراری است! لطفا از {0} دیگری استفاده نمایید..
        /// </summary>
        public static string Repetitive {
            get {
                return ResourceManager.GetString("Repetitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکمیل {0} الزامی است!.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
    }
}
